theme: jekyll-theme-cayman
title: [Adrien POLY 30 days Javascript training]
description: [Before jumping into React, I completed this excellent set of courses to stregthen my JS skills. Learned a lot of ES6 tricks.]
show_downloads: [false"]
